language: go

go:
  - 1.8.x
  - 1.9

install:
  - go get github.com/tarm/serial

script: go test -short -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
